const CARD_HEIGHT = 1479;
const CARD_WIDTH = 897;
const CARD_PREVIEW_RATIO = 4.5;
const CARD_THUMBNAIL_RATIO = 9;
const CARD_PREVIEW_WIDTH = CARD_WIDTH / CARD_PREVIEW_RATIO;
const CARD_PREVIEW_HEIGHT = CARD_HEIGHT / CARD_PREVIEW_RATIO;
const CARD_THUMBNAIL_WIDTH = CARD_WIDTH / CARD_THUMBNAIL_RATIO;
const CARD_THUMBNAIL_HEIGHT = CARD_HEIGHT / CARD_THUMBNAIL_RATIO;

export {
  CARD_HEIGHT,
  CARD_WIDTH,
  CARD_PREVIEW_RATIO,
  CARD_PREVIEW_WIDTH,
  CARD_PREVIEW_HEIGHT,
  CARD_THUMBNAIL_RATIO,
  CARD_THUMBNAIL_WIDTH,
  CARD_THUMBNAIL_HEIGHT,
};
